In [ ]:
import numpy as np

In [ ]:
list = [1,2,3,4,5,6,7,8,9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(list)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0]

1

In [ ]:
matriz[1,2]

6

In [ ]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[-9]

1

In [ ]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
dimension3 = [[[1,2],[3,4]], [[5,6], [7,8]], [[9,10], [11,12]]]
dimension3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [ ]:
dimension3 = np.array(dimension3)
dimension3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
dimension3[0]

array([[1, 2],
       [3, 4]])

In [ ]:
dimension3[0,0,1]

2

In [ ]:
dimension3[:2,::,1: ]

array([[[2],
        [4]],

       [[6],
        [8]]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=88a0fc44-9153-47d8-9fa2-e6788d3ddf7b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>