In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10,(3,3))

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr

array([[6, 7, 2],
       [8, 7, 8],
       [9, 2, 1]])

In [ ]:
arr.reshape(1,9)

array([[6, 7, 2, 8, 7, 8, 9, 2, 1]])

In [ ]:
arr.reshape(9,1)

array([[6],
       [7],
       [2],
       [8],
       [7],
       [8],
       [9],
       [2],
       [1]])

In [ ]:
np.random.randint(1,100,(3,4,3))

array([[[57, 63, 18],
        [44, 61, 83],
        [37, 40,  5],
        [85, 95, 36]],

       [[53, 60, 17],
        [37, 73, 92],
        [60, 49, 43],
        [57, 39, 23]],

       [[18, 70, 82],
        [63, 54, 77],
        [47, 14, 99],
        [60,  7, 20]]])

In [ ]:
tensorOri = np.random.randint(1,100,(3,4,3))

In [ ]:
tensorOri.shape

(3, 4, 3)

In [ ]:
tensorOri.reshape(3,1,12)

array([[[81, 67, 58, 60, 21, 62,  5, 77, 74, 21, 45, 80]],

       [[51, 63, 73, 71, 15, 25, 17, 17, 71, 65, 58, 71]],

       [[10, 19, 42, 30, 73, 38, 75,  1, 56, 40, 56, 32]]])

In [ ]:
tensorRe = tensorOri.reshape(3,1,12)

In [ ]:
tensorRe.reshape(1,2,3)

ValueError: cannot reshape array of size 36 into shape (1,2,3)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=88a0fc44-9153-47d8-9fa2-e6788d3ddf7b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>