In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,20,10)
arr

array([ 6, 11, 15, 12,  9, 17,  7,  7, 12,  3])

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[ 6, 11, 15, 12,  9],
       [17,  7,  7, 12,  3]])

In [ ]:
arr.max()

17

In [ ]:
arr.argmax()

5

In [ ]:
matriz.max(0)

array([17, 11, 15, 12,  9])

In [ ]:
matriz.argmax()

5

In [ ]:
arr.argmin(0)

9

In [ ]:
matriz.min(0)

array([ 6,  7,  7, 12,  3])

In [ ]:
matriz.argmin(0)

array([0, 1, 1, 0, 1])

In [ ]:
arr.ptp()

14

In [ ]:
arr.min()

3

In [ ]:
matriz.min(1)

array([6, 3])

In [ ]:
matriz.ptp(0)

array([11,  4,  8,  0,  6])

In [ ]:
arr.ptp()

14

In [ ]:
arr.sort()
arr

array([ 3,  6,  7,  7,  9, 11, 12, 12, 15, 17])

In [ ]:
np.percentile(arr, 50)

10.0

In [ ]:
np.median(arr)

10.0

In [ ]:
np.std(arr) ** 2

16.690000000000005

In [ ]:
np.var(arr)

16.69

In [ ]:
np.mean(arr)

9.9

In [ ]:
np.median(matriz,1)

array([ 7., 12.])

In [ ]:
a = np.array([[1,2],[3,4]])


In [ ]:
b = np.array([5,6])

In [ ]:
np.concatenate((a,b), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
b = np.expand_dims (b, axis = 0)

In [ ]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b.T

array([[5],
       [6]])

In [ ]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=88a0fc44-9153-47d8-9fa2-e6788d3ddf7b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>