In [ ]:
import numpy as np

In [ ]:
arr = np.linspace(0,10,10, dtype = 'int8')

In [ ]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
inde = arr > 5

In [ ]:
arr[inde]

array([ 6,  7,  8, 10], dtype=int8)

In [ ]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr[arr > 5] = 99

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5, 99, 99, 99, 99], dtype=int8)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=88a0fc44-9153-47d8-9fa2-e6788d3ddf7b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>