In [ ]:
import numpy as np

In [ ]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [ ]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz = np.array([[1,2,3], [4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
tensor = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[0,7,8]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 7 8]]]


3

## Crear nuevas dimensiones


In [ ]:
vector = np.array([1,2,3], ndmin = 10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1,2,3]), axis= 0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## RETO


1. Definir un tensor de 5 dimensiones
2. Sumar una dimensión en algún eje
3. Borrar dimensiones que no se usen

In [ ]:
tensorFive = np.array([[[[1,2],[3,4]]],[[[5,6],[7,8]]],[[[5,6],[7,8]]]], ndmin = 5)
print(tensor)
tensor.ndim

[[[[[1 2]
    [3 4]]]


  [[[5 6]
    [7 8]]]


  [[[5 6]
    [7 8]]]]]


5

In [ ]:
expandFive = np.expand_dims(tensorFive, axis=1)
print(expandFive)
expandFive.ndim

[[[[[[1 2]
     [3 4]]]


   [[[5 6]
     [7 8]]]


   [[[5 6]
     [7 8]]]]]]


6

In [ ]:
reduceFive = np.squeeze(expandFive)
print(reduceFive,reduceFive.ndim) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[5 6]
  [7 8]]] 3


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=88a0fc44-9153-47d8-9fa2-e6788d3ddf7b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>