## Cómo crear y manipular un array de **3 dimensiones**

Importamos Numpy

In [ ]:
import numpy as np

In [ ]:
dimension3 = [[[1,2],[3,4]], [[5,6], [7,8]], [[9,10], [11,12]]]
dimension3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

Creamos nuestro array, una manera sencilla de entender cómo funciona es por los **corchetes** que tiene.

Es como poner varias matrices juntas.
- [[1,2],[3,4]] <-- Primera matriz
- [[5,6], [7,8]] <-- Segunda matriz
- [[9,10], [11,12]] <-- Tercera matriz

Pasamos nuesta matriz por numpy

In [ ]:
dimension3 = np.array(dimension3)
dimension3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

Los ejes de 3 dimesiones son **Z, Y, X**. En ese orden los vamos a usar.
+ dimension3[Z,Y,X]

La Z representa la profundidad, en este caso los niveles que tenemos.

    [ 1,  2],
    [ 3,  4] <-- posición 0 

       [ 5,  6],
        [ 7,  8], <-- posición 1

       [ 9, 10],
        [11, 12] <--posición 2

In [ ]:
dimension3[2]

array([[ 9, 10],
       [11, 12]])

In [ ]:
dimension3[2,1]

array([11, 12])

In [ ]:
dimension3[2,1,0]

11

## ¿Cómo hacer Slicing?

Es de la misma manera que en una matriz de 2 dimensiones, simplemente le ponemos un paramétro más

In [ ]:
dimension3[:2,::,1: ]

array([[[2],
        [4]],

       [[6],
        [8]]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=88a0fc44-9153-47d8-9fa2-e6788d3ddf7b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>