### Importar librería

In [1]:
import numpy as np 

In [11]:
arr = np.linspace(1,11,16, dtype='int8') #indica (el valor de inicio, el valor de fin, cuantos valores quiero, el tipo de dato)
arr

array([ 1,  1,  2,  3,  3,  4,  5,  5,  6,  7,  7,  8,  9,  9, 10, 11],
      dtype=int8)

In [ ]:
#Validación elemento a elemento
indices_cond = arr > 5 
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
# Seleccion de elementos basados en alguna condición
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
#Usando condiciones más complejas
arr[(arr > 5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr[arr > 5] = 99 

In [ ]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)