### Importar librerías

In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

In [9]:
arr = np.arange(0,10) # devuelve una lista de numeros 
arr2 = arr.copy()


### Operaciones (aritmética simple al array)

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
1 / arr 

/tmp/ipykernel_15014/1952622374.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Operaciones entre arrays

In [25]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
arr - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [27]:
matriz = arr.reshape(2,5,-1)
matriz2 = matriz.copy()
matriz

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [29]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [31]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [33]:
np.matmul(matriz,matriz2.T) #realiza una multiplicacion de matrices obvio hay que colocar una matriz transpuesta fila * columna segun la aritemetica
#revisar operaciones de matrices y multiplicacionde matrices fila * columna

array([[ 30,  80],
       [ 80, 255]])

In [34]:
matriz @ matriz2.T #lo mismo hace esto que la linea de codigo anterior

array([[ 30,  80],
       [ 80, 255]])