### Importar librerías

In [1]:
import numpy as np 

In [9]:
arr = np.random.randint(1,10,(3,2))
arr

array([[3, 4],
       [2, 3],
       [5, 6]])

### Shape

In [10]:
arr.shape # indica cuantas filas o columnas tiene un objeto o un arreglo

(3, 2)

In [10]:
arr

array([[1, 3, 9],
       [5, 1, 7],
       [4, 5, 6]])

### Reshape

In [17]:
arr.reshape(1,6) # cambia las filas y las columnas del arreglo en este caso a 1 x 6 en contraposicion del original que es 3 x 2

array([[3, 4, 2, 3, 5, 6]])

In [10]:
arr.reshape(2,3) #aqui se cambia a 2 x3 

array([[6, 9, 8],
       [6, 9, 6]])

In [11]:
np.reshape(arr,(1,6)) # aqui se usa la libreria de numpy es lo mismo 

array([[6, 9, 8, 6, 9, 6]])

In [12]:
arr

array([[6, 9],
       [8, 6],
       [9, 6]])

In [13]:
np.reshape(arr,(2,3),'C') # aqui toma el reshape y los orderna como lo hace C en este caso por filas 

array([[6, 9, 8],
       [6, 9, 6]])

In [18]:
np.reshape(arr,(2,3),'F') # aqui hace lo mismo pero por columnas porque asi lo hace fortran

array([[6, 9, 6],
       [8, 9, 6]])

In [20]:
np.reshape(arr,(2,3),'A') # aqui define que los ordene como esta almacenado en el equipo el decide si lo usa de tipo F o C dependiendo de que lea en los datos del equipo y como este lo encuentre mas optimizado mostrar

array([[6, 9, 8],
       [6, 9, 6]])

In [29]:
arr = np.random.randint(1,9,(4,6))

In [30]:
arr

array([[4, 7, 7, 2, 5, 7],
       [6, 7, 4, 4, 5, 3],
       [2, 8, 2, 8, 6, 4],
       [8, 6, 6, 5, 8, 6]])

In [31]:
arr.reshape(2,-1)

array([[4, 7, 7, 2, 5, 7, 6, 7, 4, 4, 5, 3],
       [2, 8, 2, 8, 6, 4, 8, 6, 6, 5, 8, 6]])

La línea de código arr.reshape(2, -1) se utiliza para cambiar la forma de un array NumPy a una nueva forma especificada. En este caso, la nueva forma es una matriz de 2 filas y un número de columnas que se infiere del tamaño total del array original y la primera dimensión.

In [36]:
arr.reshape(2,2,-1)

array([[[4, 7, 7, 2, 5, 7],
        [6, 7, 4, 4, 5, 3]],

       [[2, 8, 2, 8, 6, 4],
        [8, 6, 6, 5, 8, 6]]])

Dimension -1: El uso de -1 en la tercera dimensión de newshape indica a la función reshape que el número de elementos en esa dimensión debe inferirse del tamaño total del array original y las dos primeras dimensiones. Esto significa que el array se redistribuirá en las 2 filas y 2 columnas de la nueva forma, manteniendo el mismo número total de elementos.